version: '3'
services:
  monitor.dev:
    build:
     context: containers/monitor
     args:
      - NIFI_URL=${NIFI_URL}
      - NIFI_SUBFOLDER=${NIFI_SUBFOLDER}
    image: monitor
    networks:
     - dev
    hostname: monitor
    domainname: dev
    ports:
     - "8080:8080"
     - "8500:8500"
    volumes:
     - ./data:/data
  web-static.dev:
    build: 
      context: containers/web-static
    image: web-static
    networks:
     - dev
    environment:
     - SCRIPT=web.sh
  web-service.dev:
    build: 
      context: containers/web-service
    image: web-service
    networks:
     - dev
    environment:
     - SCRIPT=web.sh
  zeppelin.dev:
    build:
     context: containers/zeppelin
     args:
      - SPARK_URL=${SPARK_URL}
      - SPARK_SUBFOLDER=${SPARK_SUBFOLDER}
      - ZEPPELIN_URL=${ZEPPELIN_URL}
      - ZEPPELIN_SUBFOLDER=${ZEPPELIN_SUBFOLDER}
    image: zeppelin
    networks:
     - dev
    ports:
     - "8081:8080"
     - "4040:4040"
    volumes:
     - ./data:/data

networks:
  dev:
    driver: bridge
