version: '2'
services:
  monitor.dev:
    build:
     context: containers/base
     args:
      - NIFI_URL=${NIFI_URL}
      - NIFI_SUBFOLDER=${NIFI_SUBFOLDER}
    image: base
    networks:
     - dev
    hostname: monitor
    domainname: dev
    environment:
     - MODE=master
    ports:
     - "8080:8080"
     - "8500:8500"
    volumes:
     - ./data:/data
  web-static.dev:
    depends_on:
     - monitor.dev
    build: 
      context: containers/web-static
    image: web
    networks:
     - dev
    environment:
     - MODE=slave
     - SCRIPT=web.sh
  web-service.dev:
    depends_on:
     - monitor.dev
    build: 
      context: containers/web-AccountBalance
    image: web
    networks:
     - dev
    environment:
     - MODE=slave
     - SCRIPT=web.sh
  zeppelin.dev:
    build:
     context: containers/zeppelin
     args:
      - SPARK_URL=${SPARK_URL}
      - SPARK_SUBFOLDER=${SPARK_SUBFOLDER}
      - ZEPPELIN_URL=${ZEPPELIN_URL}
      - ZEPPELIN_SUBFOLDER=${ZEPPELIN_SUBFOLDER}
    image: zeppelin
    networks:
     - dev
    ports:
     - "8081:8080"
     - "4040:4040"
    volumes:
     - ./data:/data

networks:
  dev:
    driver: bridge
